---
- name: Process ComposeInfo
  compose_info:
    compose_path: "/data/{{ topic_name }}/compose"
  register: results

- name: Set Composeinfo
  set_fact:
    compose_info: "{{ results.compose_info }}"

- name: Set os_major_modified and harness
  set_fact:
    os_major_modified: "{{ compose_info.osmajor }}"
    harness: restraint

- name: Use RHEL8 harness for RHEL9 and RHEL10
  set_fact:
    os_major_modified: "RedHatEnterpriseLinux8"
  when:
    - compose_info.osmajor == "RedHatEnterpriseLinux9" or
      compose_info.osmajor == "RedHatEnterpriseLinux10"

- name: Don't add beakerlib for RHEL-9, CentOS 9, RHEL-10, or CentOS-10
  set_fact:
    harness: "{{ harness }} beakerlib"
  when:
    - compose_info.osmajor not in ["CentOSStream9", "CentOSStream10",
                                   "RedHatEnterpriseLinux9",
                                   "RedHatEnterpriseLinux10"]

- name: Verify correct component is downloaded
  assert:
    that:
      - compose_info.compose_id == item.display_name
  when: item.type == 'compose'
  loop: "{{ components }}"
